name: Publish Release
on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9]

    name: Python ${{ matrix.python }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Tag
        id: tag
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - uses: robinraju/release-downloader@v1.8
        with:
          tag: v${{ steps.tag.outputs.version }}
          fileName: tos.jsonl.gz
      - name: Extract Databases
        run: |
          mkdir data
          zcat tos.jsonl.gz > data/tos.jsonl
          rm tos.jsonl.gz
      - name: Set Version
        run: |
          sed -ri 's/version = "(.*)"/version = "${{ steps.tag.outputs.version }}"/' pyproject.toml
          sed -i 's/"dev"/"${{ steps.tag.outputs.version }}"/' src/weboptout/__init__.py
      - name: Install Requirements
        run: |
          pip install poetry
      - name: Create Package
        run: |
          poetry build
      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/weboptout-*
