# Python Release
#
# Automatically build and publish the package from the supported Python 3.x version.
#

name: release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
    name: Python ${{ matrix.python }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Tag
        id: tag
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Set Version
        run: |
          sed -ri 's/version = "(.*)"/version = "${{ steps.tag.outputs.version }}"/' pyproject.toml
          sed -i 's/"dev"/"${{ steps.tag.outputs.version }}"/' src/weboptout/__init__.py
      - name: Install Requirements
        run: |
          pip install poetry
      - name: Create Package
        run: |
          poetry build
      - name: Publish Package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish -n
